#!/bin/sh

versionname=$(grep 'vvvv' interface.cpp)

tar -cf $versionname.tar *.cpp *.h *.pro Makefile *.jpg backup.sh
gzip $versionname.tar
mv $versionname.tar.gz "/media/88FF-021A/codebackups/"

make

./dclient2
